# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9caff4ec330eabc896fa2482f65c0a071ce51b316f91fbc64282522e585751bebd416a85f697ff71c2abad9b04a12912af01fda1c4e2c533277301f2bb3a9347

test:
  secret_key_base: 39ac9275ec640631a81d031baa196253c374146a5ed777a6b0c76621958b22f530ef74fa0f4bb48b43f78107ca51271319e66d9579c89ba992e7c82ace243b5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
